### ISSUE TITLE
Make ipv6 entries more flexible

### ISSUE THREAD

**Issue by kTitan** [arillso/ansible.hosts#5]
I just tried the module on a host, which has no default ipv6 configured, but has ipv6 enabled on the loopback interface. (which is needed for a software)
The result was, that the ipv6 localhost entries were removed.

That happened because ansible_default_ipv6.address are not defined. 

I would suggest that you create an "force" option for that, or at least check also if "ansible_lo.ipv6" is defined or not.

Thank you.

**Comment by sbaerlocher** [comment]
Both options are now built in.

If lo is defined for ipv6, the entries are set automatically. Setting `hosts_ipv6: false` prevents ipv6 entries from being created.

**Comment by kTitan** [comment]
I just tried the develop branch with the modifications.

There is currently a problem in the hosts.j2 template.
Around line 19 you are using
`hostvars[inventory_hostname]['ansible_default_ipv6']['address']` 
directly, without checking if it defined. 

Because of that it did not work on my test host:
`FAILED! => {"changed": false, "msg": "AnsibleUndefinedVariable: 'dict object' has no attribute 'address'"}`

**Comment by sbaerlocher** [comment]
I have now fixed it in the new develop version.
